### ISSUE TITLE
Category: if not exists...

### ISSUE THREAD

**Issue by k0nsti** [k0nsti/konsum#948]
example from main page doesn work.
If the category does not exists, not new will be created. Bug or wanted feature?

bin/konsum --config=config insert ev 90091.3 '2019-06-22T13:44:17'
(node:23606) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeValue' of undefined
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by arlac77** [comment]
There is no auto creation of categories in place.
